#!/bin/bash

set -e

FILE_ENV=$1

if [[ -z "$FILE_ENV" ]]; then
    ___mysqlimport.sh
    exit 0
fi

if [[ -f $FILE_ENV ]]; then
    enve -f $FILE_ENV ___mysqlimport.sh
else
    echo "ERROR: env file \`$FILE_ENV\` was not found"
    exit 1
fi
