name: release-v8.0
on:
  push:
    tags:
    - 'v8.0.[0-9]+'
    - 'v8.0.[0-9]+-beta.[0-9]+'
    paths:
      - 8.0/**

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: joseluisq/mysql-client
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Prepare Docker envs
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          file: 8.0/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            VERSION=${{ env.VERSION }}
